apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-petclinic-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-petclinic
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: spring-petclinic
          image: your-registry.com/spring-petclinic:latest  # Replace with your own registry or local Docker image
          ports:
            - containerPort: 8080
      # Optional: Add if you are using self-hosted nodes and want to target specific ones
      # nodeSelector:
      #   kubernetes.io/hostname: your-node-name
      # tolerations:
      #   - key: "dedicated"
      #     operator: "Equal"
      #     value: "spring"
      #     effect: "NoSchedule"
