# manifests/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: spring-petclinic-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8080
  selector:
    app: spring-petclinic
